### ISSUE TITLE
Release dev-master?

### ISSUE THREAD

**Issue by visto9259** [Laminas-Commons/LmcUser#23]
We should release `dev-master`.

What should be the version number?

3.0.0. is still the ZfcUser code base.
Should it be 3.1.0? Or should we make it 4.0?

Version 4 would seem to indicate new functionality but this is only a migration to Laminas with no new functionality.

I think that 3.1.0 would be better with solid documentation explaining that this release has breaking changes from 3.0.0

**Comment by jroedel** [comment]
Hi, just to throw in my two cents, I'd slightly prefer 4.0 as a casual user of the repository for years. I think it just makes it very clear that this is where the laminas code starts.

Thanks a ton for porting this over. I try to maintain a repository extending ZfcUser functionality at jroedel/zf2-juser. I hope to upgrade to this laminas soon.

**Comment by matwright** [comment]
I see merit in arguments for both 4.0.0 and 3.1.0.

I agree that it would be much clearer that this is a major breaking changes release if we up the major version to 4.
But, I accept, also, that this release does not constitute new functionality.

Therefore, I feel that 3.1.0 would be the correct path to take. But, I'll add a makeshift poll in new message below and we
can release in a few days based on any further feedback from users.

**Comment by matwright** [comment]
🎉  3.1.0

🚀  4.0.0

**Comment by visto9259** [comment]
I reiterate my preference for 3.1.
The change in namespace and other strings from zfc to lmc goes without saying.  If you are installing a package called Laminas-Commons/LmcUser, it’s because you are migrating to Laminas and you are expecting to make changes in class names.

**Comment by matwright** [comment]
I'll release and tag 3.1
